services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - path: .env.local
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ./.data:/workspace/.data

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"
